GET http://localhost:3000/ads-orm

###

GET http://localhost:3000/ads-orm/Bordeaux

###

DELETE http://localhost:3000/ads-orm/40

###

PUT http://localhost:3000/ads-orm/september

###

GET http://localhost:3000/ads-orm/avg-paris

###

POST http://localhost:3000/ads-orm
Content-Type: application/json

{
  "title": "Ad test",
  "description": "Description 1",
  "owner": "Owner 1",
  "price": 100,
  "picture": "http://www.google.com",
  "location": "Location 1",
  "categoryId": 1,
  "tags": ["tag1", "tag2"]
}

###

GET http://localhost:3000/ads-orm/avg-location

###

DELETE http://localhost:3000/ads-orm/10

###

PUT http://localhost:3000/ads-orm/324
Content-Type: application/json

{
  "title": "Ad test updated",
  "description": "Description 1",
  "owner": "Owner 1",
  "price": 200,
  "picture": "http://www.google.com",
  "location": "Location 1",
  "categoryId": 1,
  "tags": ["tag3", "tag4"]
}

###

GET http://localhost:3000/ads-orm/tags/neuf