GET http://localhost:3000/movies/count

####

GET http://localhost:3000/movies/totalBudget

###

GET http://localhost:3000/movies?minYear=1970

###

GET http://localhost:3000/movies?requestedTime=14

###

GET http://localhost:3000/movies?minYear=2020&requestedTime=16


###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "Title": "Test",
  "Year": "2020",
  "Price": 100,
  "Hours": "14:00"
}

###

PUT http://localhost:3000/movies
Content-Type: application/json

{
  "ID": "28",
  "Title": "Test updateded",
  "Year": "2010",
  "Price": 101,
  "Hours": "15:00"
}

### 

DELETE http://localhost:3000/movies
Content-Type: application/json

{
  "IDS": [179, 180]
}