GET http://localhost:3000/ads/

###

POST http://localhost:3000/ads/
Content-Type: application/json

{
  "title": "Ad 1",
  "description": "Description 1",
  "owner": "Owner 1",
  "price": 100,
  "picture": "http://www.google.com",
  "location": "Location 1"
}

###

DELETE http://localhost:3000/ads/2

###

PUT http://localhost:3000/ads/3
Content-Type: application/json

{
  "title": "Ad 2",
  "description": "Description 2",
  "owner": "Owner 2",
  "price": 200,
  "picture": "http://www.google.com",
  "location": "Location 2"
}