
GET http://localhost:3001/api/categories-orm

###

GET http://localhost:3001/api/categories-orm/1

###

GET http://localhost:3001/api/categories-orm/ads/1

###

GET http://localhost:3001/api/categories-orm/multiple/autre,voiture

###

GET http://localhost:3001/api/categories-orm/avg/autre

###

GET http://localhost:3001/api/categories-orm/search/v

###

POST http://localhost:3001/api/categories-orm
Content-Type: application/json

{
  "title": "Test category",
  "description": "Description test 1",
  "owner": "Guillaume",
  "price": 100,
  "picture": "http://www.google.com",
  "location": "Location 1",
  "category": "nouveau2"
}