GET http://localhost:3001/api/categories/autre

###

GET http://localhost:3001/api/categories/multiple/autre,vetement,voiture

###

GET http://localhost:3001/api/categories/avg/vetement

###

GET http://localhost:3001/api/categories/search/ve

###

POST http://localhost:3001/api/categories
Content-Type: application/json

{
  "title": "Test category",
  "description": "Description test 1",
  "owner": "Guillaume",
  "price": 100,
  "picture": "http://www.google.com",
  "location": "Location 1",
  "category": "nouveau2"
}